# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'sqflite', '~> 2.3.3'
  pod 'path_provider', '~> 2.1.3'
  pod 'Firebase/Core', '~> 8.0.0'
  pod 'Firebase/Auth', '~> 8.0.0'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
